<table cellspacing=1 cellpadding=1 width=450 bgcolor=#990000 border=1 bordercolor=#990000>
	<tr>
		<td bgcolor=#000000>
			<font face=tahoma color=#ffffff size=2>
			<center><b>Contact</b></center>
			</font>
		</td>
	</tr>
	<tr>
		<td bgcolor=#000000>
		<form type=post action=emailadmin.php>
		<font face=tahoma size=2>Admin:</font>
			<select name=contact>
			<option selected value=ns>-----------</option>
			<option value=Human>Mako</option>
			<option value=Orc>Shredder</option>
			<option value=Dwarf>Cyrus</option>
			</select>
		<br><br>
		<textarea bordercolor: #990000 rows=15 cols=25 wrap></textarea>
		<br><br>
		<input class=button type=submit name=signup value="Sign-Up (click only once)">
			
		</td>
	</tr>
</table>
</form>
