<table cellspacing=1 cellpadding=1 width=450 bgcolor=#990000 border=1 bordercolor=#990000>
	<tr>
		<td bgcolor=#000000>
			<font face=tahoma color=#ffffff size=2>
			<center><b>Bug Reporting Guidelines</b></center>
			</font>
		</td>
	</tr>
	<tr>
		<td bgcolor=#000000><form type=post action=checksignup.php>
			<table>
			<tr><td class=signup colspan=2><b>Read this before wring a bug report.</b></td></tr>
			<tr><td class=signup colspan=2>These are some tips for writing a good bug report. Good bug reports usually get fixed faster because it is easier to understand what the problem is.</td></tr>
			<tr><td>&nbsp; </td><td>&nbsp; </td></tr>

			<tr><td class=signup width=30 valign=top>#1: </td><td class=signup>The bug that you are reporting must be able to be reproduced. If we cannot reproduce it ourselves, we will not be able to find the bug. Provide as many details as you can on how to reproduce the bug.</td></tr>
			<tr><td>&nbsp; </td><td>&nbsp; </td></tr>

			<tr><td class=signup valign=top>#2:</td><td class=signup>Be as specific as possible. If you say,<br><br>
			<b>Armor page does not work.</b><br><br>

			only in your bug report, we will not be able to fix it because we will not know what the problem is. However, if you say,<br><br>
			<b>When I click on Construct for _____ Armor, it does not construct. It just goes back to the Construct button. I was able to construct all of the other armors except for _____.</b><br><br>

			That is a very useful bug report because it gives details on what happens when they try to construct an armor. This bug will probably get fixed faster because it will be so easy to find, giving all of the details.</td></tr>
			<tr><td>&nbsp; </td><td>&nbsp; </td></tr>
			<tr><td class=signup align=center colspan=2><a href=http://sourceforge.net/tracker/?group_id=63460&atid=504052>Click here to report a bug</a></td></tr>
			</table>
		</td>
	</tr>
</table>
</form>
