<table cellspacing=1 cellpadding=1 width=450 bgcolor=#990000 border=1 bordercolor=#990000>
	<tr>
		<td bgcolor=#000000>
			<font face=tahoma color=#ffffff size=2>
			<center><b>Staff</b></center>
			</font>
		</td>
	</tr>
	<tr>
		<td bgcolor=#000000><form type=post action=checksignup.php>
			<table width=100%>
				<tr>
					<td class=signup width=35%>Jon Ursenbach (Mako):</td>
					<td class=signup align=left width=35%>&nbsp; Co-Founder/Main Coder</td>
					<td class=signup align=left>
						<a href="aim:goim?screenname=medbatmako&message=Hello+Mako"><img src="images/aim.gif" border=0 alt="Message Mako"></a>&nbsp;
						<a href="mailto:mako@medievalbattles.com"><img src="images/email.gif" border="0" alt="E-mail Mako"></a>
					</td>
				</tr>
				<tr>
					<td class=signup>Mike Day (Shredder):</td>
					<td class=signup>&nbsp; Sabin Administrator</td>
					<td class=signup align=left>
						<a href="aim:goim?screenname=smshredder&message=Hello+Shredder"><img src="images/aim.gif" border="0" alt="Message Shredder"></a>&nbsp;
						<a href="mailto:shredder@medievalbattles.com"><img src="images/email.gif" border="0" alt="E-mail Shredder"></a>
					</td>
				</tr>

			</table>
		</td>
	</tr>
</table>
</form>
