<table cellspacing=1 cellpadding=1 width=450 bgcolor=#990000 border=1 bordercolor=#990000>
	<tr>
		<td bgcolor=#000000>
			<font face=tahoma color=#ffffff size=2>
			<center><b>Staff</b></center>
			</font>
		</td>
	</tr>
	<tr>
		<td bgcolor=#000000><form type=post action=checksignup.php>
			<table>

			<tr><td class=signup>Jon Ursenbach (Mako):</td><td class=signup>&nbsp; Main Coder</td></tr>
			<tr><td class=signup>&nbsp;</td><td class=signup>&nbsp; Co-Founder</td></tr>
			<tr><td>&nbsp; </td><td>&nbsp; </td></tr>

			<tr><td class=signup>Mike Day (Shredder):</td><td class=signup>&nbsp; Sabin Administrator</td></tr>
			<tr><td>&nbsp; </td><td>&nbsp; </td></tr>

			<tr><td class=signup>Marco Leggi (Cyrus):</td><td class=signup>&nbsp; Equation Creator</td></tr>
			<tr><td class=signup>&nbsp;</td><td class=signup>&nbsp; Doc Writer</td></tr>
			</table>
		</td>
	</tr>
</table>
</form>
